### PR TITLE
Updates icon, link button shortcode to prepare for migration to plugin

### PR DESCRIPTION
**Pull request by timurtripp**
This update:
- Updates icon shortcode. Resolves CuBoulder/ucb_migration_shortcodes#31
- Updates link button shortcode. Resolves CuBoulder/ucb_migration_shortcodes#56

### CODE REVIEW

**Comment by timurtripp** [comment]
Buttons are coming across correctly but the icon migration is still a blocker. Marking as draft for now.

**Comment by timurtripp** [comment]
Icon test shortcodes:
```
[icon shape="fa-star-o" size="regular" color="inherit" wrapper="none" /] [icon shape="fa-star-o" size="fa-lg" color="inherit" wrapper="none" /] [icon shape="fa-star-o" size="fa-2x" color="inherit" wrapper="none" /] [icon shape="fa-star-o" size="fa-3x" color="inherit" wrapper="none" /] [icon shape="fa-star-o" size="fa-4x" color="inherit" wrapper="none" /] [icon shape="fa-star-o" size="fa-5x" color="inherit" wrapper="none" /]

[icon shape="fa-rocket" size="fa-5x" color="black" wrapper="none" /] [icon shape="fa-rocket" size="fa-5x" color="white" wrapper="none" /] [icon shape="fa-rocket" size="fa-5x" color="light-gray" wrapper="none" /] [icon shape="fa-rocket" size="fa-5x" color="gray" wrapper="none" /] [icon shape="fa-rocket" size="fa-5x" color="dark-gray" wrapper="none" /] [icon shape="fa-rocket" size="fa-5x" color="gold" wrapper="none" /]

[icon shape="fa-leaf" size="fa-4x" color="gray" wrapper="square" /] [icon shape="fa-leaf" size="fa-4x" color="gold" wrapper="circle" /]  [icon shape="fa-leaf" size="fa-4x" color="black" wrapper="rounded" /]

[icon shape="fa-drupal" /] [icon shape="fa-shield" /]
```

**Comment by timurtripp** [comment]
Link button test shortcodes:
```
[button icon="fa-star-o" url="https://iiod.io"]Play a fun browser game![/button]]

[button url="https://iiod.io" color="blue" size="regular" style="regular"]Play a fun browser game![/button][button url="https://iiod.io" color="gold" size="regular" style="regular"]Play a fun browser game![/button][button url="https://iiod.io" color="gray" size="regular" style="largeregularPlay a fun browser game![/button][button url="https://iiod.io" color="black" size="regular" style="regular"]Play a fun browser game![/button][button url="https://iiod.io" color="white" size="regular" style="regular"]Play a fun browser game![/button]

[button url="https://iiod.io" color="blue" size="small" style="regular" icon="fa-arrow-right"]Play a fun browser game![/button][button url="https://iiod.io" color="gold" size="small" style="regular" icon="fa-arrow-right"]Play a fun browser game![/button][button url="https://iiod.io" color="gray" size="small" style="regular" icon="fa-arrow-right"]Play a fun browser game![/button][button url="https://iiod.io" color="black" size="small" style="regular" icon="fa-arrow-right"]Play a fun browser game![/button][button url="https://iiod.io" color="white" size="small" style="regular" icon="fa-arrow-right"]Play a fun browser game![/button]

[button url="https://iiod.io" color="blue" size="small" style="full"]Play a fun browser game![/button][button url="https://iiod.io" color="gold" size="small" style="full"]Play a fun browser game![/button][button url="https://iiod.io" color="gray" size="small" style="full"]Play a fun browser game![/button][button url="https://iiod.io" color="black" size="small" style="full"]Play a fun browser game![/button][button url="https://iiod.io" color="white" size="small" style="full"]Play a fun browser game![/button]

**Review by jnicholCU — APPROVED** [review]
Both updates for icons and buttons work well. 
Buttons with icons comes through clearly. 
Should all work great for the migration.

**Pull request merged**
